stages:
- nuget

nuget:
  tags:
  - docker
  image: microsoft/dotnet:2.1-sdk
  stage: nuget
  before_script:
    - apt-get update
      && apt-get install -y python3-pip python3-dev
      && cd /usr/local/bin
      && ln -s /usr/bin/python3 python
      && pip3 install --upgrade pip
  only:
    - nuget
  script:
    - mkdir scripts 
      && cd scripts
      && wget "https://raw.githubusercontent.com/amir734jj/resolve-nuget-version/master/app.py"
      && cd ../
    
    - echo ${PACKAGE_NAME} | python3 "scripts/app.py"
    - dotnet build -c Release
    - echo "Calculated version:"
    - python3 "scripts/app.py" ${PACKAGE_NAME} | dotnet pack ./StreamRipper -c Release -o "${PWD}/artifacts/" --version-suffix 
    - dotnet nuget push --force-english-output -s https://api.nuget.org/v3/index.json -k "${NUGET_API_KEY}" ./artifacts/*.nupkg
  artifacts:
    expire_in: 31d
    paths:
    - artifacts/*
