stages:
- build
- nuget

build:
  tags:
  - docker
  image: microsoft/dotnet:2.2-sdk
  stage: build
  script:
    - dotnet build -c Release

nuget:
  tags:
  - docker
  image: microsoft/dotnet:2.2-sdk
  stage: nuget
  only:
  - nuget
  script:
  - cd scripts && wget "https://raw.githubusercontent.com/amir734jj/resolve-nuget-version/master/app.py"
  - python3 "scripts/app.py" ${NAME}
  - dotnet build -c Release
  - echo "Calculated version:"
  - python3 "scripts/app.py" ${NAME}
  - python3 "scripts/app.py" ${NAME} | dotnet pack ./${NAME} -c Release -o "${PWD}/artifacts/" --version-suffix 
  - dotnet nuget push --force-english-output -s https://api.nuget.org/v3/index.json -k "${NUGET_API_KEY}" ./artifacts/*.nupkg
  artifacts:
    expire_in: 31d
    paths:
    - artifacts/*
