stages:
- build
- nuget

build:
  tags:
  - docker
  image: microsoft/dotnet:2.1-sdk
  stage: build
  script:
    - dotnet build -c Release

nuget:
  tags:
  - docker
  image: microsoft/dotnet:2.1-sdk
  stage: nuget
  only:
    - nuget
  variables: 
    
  script:
    - mkdir scripts 
      && cd scripts
      && wget "https://raw.githubusercontent.com/amir734jj/resolve-nuget-version/master/app.py"
      && cd ../
    
    - python3 "scripts/app.py" "$PACKAGE_NAME"
    - dotnet build -c Release
    - echo "Calculated version:"
    - cd Stream-ripper
    - python3 "../scripts/app.py" PACKAGE_NAME | dotnet pack ./StreamRipper -c Release -o "${PWD}/artifacts/" --version-suffix 
    - dotnet nuget push --force-english-output -s https://api.nuget.org/v3/index.json -k "${NUGET_API_KEY}" ./artifacts/*.nupkg
  artifacts:
    expire_in: 31d
    paths:
    - artifacts/*
